### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/jenkins-playground#1]
- [ ] Setup Jenkins with Packer

- [x] Run first Jenkins Job with Jenkinsfile

- [x] Add a slave node

**Comment by xuyuji9000** [comment]
idle
